# Generated by Django 3.2.9 on 2022-02-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='number',
        ),
    ]
